functions/pgulid.sql, schema/incidents.hcl, views/001_roles.sql, views/008_incident_history_triggers.sql
Fixes https://github.com/flanksource/incident-commander/issues/99
=>  feat: add postgrest_anon role 

views/001_postgrest.sql
=> fix: reload postgrest schema cache after DDL updates

views/003_analysis_views.sql, views/006_config_views.sql
Fixes: https://github.com/flanksource/config-db/issues/89
=> chore: use deleted_at for config_item queries

views/015_job_history_status.sql
Example query res: 
```
select id, name, job_created_at, job_status FROM templates_with_status
+--------------------------------------+--------------+----------------------------+------------+
| id                                   | name         | job_created_at             | job_status |
|--------------------------------------+--------------+----------------------------+------------|
| 36953751-d008-456e-a8f8-119b870ab76f | aditya-thebe | 2023-03-14 13:44:22.007021 | FINISHED   |
| 018678f9-d892-989a-0822-fcf087028007 | petclinic    | 2023-03-14 13:44:22.019511 | FINISHED   |
+--------------------------------------+--------------+----------------------------+------------+
```
Closes https://github.com/flanksource/duty/issues/52
=> added job history status view

models/checks.go, schema/checks.hcl, views/016_check_status.sql
Closes https://github.com/flanksource/canary-checker/issues/874
=> feat: new view and 2 new tables for check_statuses aggregation

models/components.go
required by incident commander
=> added GetAsEnvironment() method to component model

models/checks.go
=> fix: use local time for checks deleted_at

schema/checks.hcl, schema/components.hcl, schema/config.hcl, schema/incidents.hcl, schema/teams.hcl
=> chore: add deleted_at fields for tables

views/010_topology.sql
Resolves https://github.com/flanksource/duty/issues/116
=> Added team names in topology view

functions/incident_ids.sql, incident_summary_test.go, models/incidents.go, schema/incidents.hcl, views/009_incident_views.sql
https://github.com/flanksource/incident-commander/issues/123
=> added incident_id column

models/canary.go, schema/checks.hcl
Fixes: https://github.com/flanksource/duty/issues/115
=> chore: remove schedule from canary

models/config.go
Analysis should be `map[string]any`
=> use JSONMap instead of JSONStringMap

views/011_users.sql
Fixes: https://github.com/flanksource/incident-commander/issues/319
=> feat: create view for user roles

schema/properties.hcl
Fixes: https://github.com/flanksource/incident-commander/issues/322
=> feat: add properties table

topology.go, views/010_topology.sql
* teams in topology query
* log selectors in topology view
=> fix: topology query

models/components.go, models/topology.go, types/config.go, types/log_selector.go, types/types.go, views/005_component_views.sql
Resolves: https://github.com/flanksource/duty/issues/150
=> feat: components with log selector view

check_summary_test.go, fixtures/dummy/agents.go, fixtures/dummy/all.go, fixtures/dummy/canaries.go, fixtures/dummy/checks.go, models/canary.go, models/checks.go, models/components.go, models/config.go, schema/checks.hcl, schema/components.hcl, schema/config.hcl, schema/vars.hcl, topology_test.go, views/002_seed.sql
Fixes: https://github.com/flanksource/incident-commander/issues/342
=> fix: add agent_id in canaries unique constraint

types/types.go, views/005_component_views.sql
* Fixed a bug in `GormValue()` that stored nil as the string "null" instead of `<null>`
=> modified components_with_logs view

views/007_events.sql
Resolves: https://github.com/flanksource/duty/issues/163
```
select * FROM failed_push_queue
+----------------+-------------+------------------+-------------------------------+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| table          | error_count | average_attempts | first_failure                 | latest_failure                | most_common_error                                                                                                                               |
|----------------+-------------+------------------+-------------------------------+-------------------------------+-------------------------------------------------------------------- …
```
=> added views for event_queue for debugging

schema/incidents.hcl, views/007_events.sql
* add trigger to push any changes on the teams table to the event queue
=> feat: add notification table

views/008_incident_history_triggers.sql
Resolves: https://github.com/flanksource/incident-commander/issues/405
=> feat: add trigger | when done definition is added, log it to incident

check_summary.go, fixtures/expectations/check_status_summary.json, models/checks.go, views/006_config_views.sql
Resolves: https://github.com/flanksource/duty/issues/44
Resolves: https://github.com/flanksource/duty/issues/21
=> feat: new views to summarize change count by type and analysis count by severity. & add component id to check summary.

views/006_config_views.sql
Fixes: https://github.com/flanksource/flanksource-ui/issues/1237
=> fix: sort config changes by component using created_at

views/17_canary_delete.sql
Resolves: https://github.com/flanksource/duty/issues/195
=> feat: trigger to soft delete checks and check component relationship on

models/canary.go, models/checks.go, models/comments.go, models/evidences.go, models/hypotheses.go, models/incidents.go, models/notifications.go, models/responders.go, schema/incidents.hcl, schema/notifications.hcl, views/007_events.sql
* Added new notification table and removed previous one
=> feat: added new events to the event queue for notification

views/005_component_views.sql
Resolves: https://github.com/flanksource/duty/issues/211
=> feat: added lookup_components_by_check

views/003_analysis_views.sql
Resolves: https://github.com/flanksource/duty/issues/218
=> feat: analysis_by_component should only return open analyses

views/006_config_views.sql
I need this to be able to fetch the change details via it's ID
=> feat: add config change id for to the changes_by_component view

views/013_updated_at_column_trigger.sql
Fixes: https://github.com/flanksource/duty/issues/227
=> feat: canaries updated_at only reflects spec changes

check_summary.go, fixtures/expectations/check_status_summary.json, models/checks.go, views/013_check_summary.sql
Resolves: https://github.com/flanksource/canary-checker/issues/1144
=> feat: added check summary for component func

views/015_job_history.sql
Fixes: https://github.com/flanksource/duty/issues/228
=> feat: add last_runtime in canaries_with_status view

views/015_job_history.sql
Resolves: https://github.com/flanksource/duty/issues/236
=> feat: new notification summary view

schema/teams.hcl
https://github.com/flanksource/incident-commander/issues/487
=> feat: add unique email index in people table

views/006_config_views.sql
Resolves: https://github.com/flanksource/duty/issues/193
=> feat: add severity summary to config summary view

fixtures/dummy/all.go, fixtures/dummy/config.go, fixtures/dummy/incidents.go, suite_test.go
Introduces new way to get the same dummy fixtures but with random IDs. This way we can generate as many dummy fixtures as we want for multiple agents.
The old fixtures with hardcoded ids are still there.
=> feat: introduce dummy data generator that assigns random ID to the models

views/007_events.sql
=> fix: add conflict handling for check updates in event queue

context/context.go, context/context_test.go, go.mod, go.sum, hack/migrate/go.mod, hack/migrate/go.sum, job/job.go, models/job_history.go, models/people.go, upstream/client.go, upstream/jobs.go, upstream/reconcile.go, upstream/upstream.go
Depends on https://github.com/flanksource/commons/pull/84
=> feat: add job runtime and job struct

models/connections.go
* create consistent credential file name to avoid creation of lots of credential files every run
=> fix: create connection credential dir if not exist

types/types.go
We can use this easily set db text fields  to null
Current usecase is status_reason field, which we unmarshal from a json, to set it to null, we have to explicitly update it because of the way gorm handles zero fields
With this type, if the json has empty string, the gorm model will treat it as `NULL`
=> feat: add null string type

models/integrations.go, models/logging_backends.go, models/source.go, models/topology.go, schema/components.hcl, schema/logging_backends.hcl, tests/fixtures/dummy/topologies.go, tests/integrations_test.go, views/015_job_history.sql, views/024_integrations.sql
resolves: https://github.com/flanksource/duty/issues/356
=> feat: integrations view

migrate/migrate.go
resolves: https://github.com/flanksource/duty/issues/346
=> feat: log migration of scripts

views/015_job_history.sql
resolves: https://github.com/flanksource/duty/issues/412
=> fix: add interval to canaries_with_status

models/event_queue.go, tests/event_queue_test.go, views/007_events.sql
resolves: https://github.com/flanksource/duty/issues/411
resolves: https://github.com/flanksource/duty/issues/410
=> feat: push_queue_summary & event_queue_summary

query/config_cache.go
Also added a new function FindConfigIDs just to fetch the IDs and cache those
=> feat: add caching to find configs function

models/artifacts.go, schema/artifacts.hcl, schema/playbooks.hcl, tests/fixtures/dummy/all.go, tests/fixtures/dummy/artifacts.go, tests/upstream_test.go, upstream/commands.go, upstream/jobs.go, upstream/reconcile.go, upstream/upstream.go
Fixes https://github.com/flanksource/mission-control/issues/754
=> feat: upstream push for artifacts

views/006_config_views.sql
Add views that will allow us to filter config insights and changes by config type
=> chore: add config_analysis_items and config_changes_items with config type

models/agents.go, tests/agents_test.go, views/022_agents.sql
resolves: https://github.com/flanksource/mission-control/issues/803
=> feat: revoke access tokens of deleted agents

models/config.go, tests/config_changes_test.go, tests/config_relationship_test.go, views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/445
resolves: https://github.com/flanksource/duty/issues/171
=> feat: recursive changes (upstream/downstream) & recursive related configs

go.mod, go.sum, models/components.go, models/config.go, upstream/commands.go
fix for https://github.com/flanksource/mission-control/pull/844
=> fix: save iteratively with retries

views/015_job_history.sql
This is related to this -> https://github.com/flanksource/flanksource-ui/issues/1728
=> feat: add a job_last_failed column for tables with summary views

query/config_changes.go, tests/config_changes_test.go, tests/config_relationship_test.go, views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/601
resolves: https://github.com/flanksource/duty/issues/600
=> fix: remove duplicates in related configs recursive

.gitignore, go.mod, query/resource_selector.go, tests/query_resource_selector_test.go, types/resource_selector.go, types/resource_selector_test.go
resolves: https://github.com/flanksource/duty/issues/588
related: https://github.com/flanksource/duty/issues/625
=> feat: resource selector Search and tests

views/027_connections.sql
Fixes: https://github.com/flanksource/duty/issues/628
=> feat: add connection list view

query/config_cache.go, tests/config_traversal_test.go
Fixes: https://github.com/flanksource/duty/issues/633
=> chore: update config traversal to handle new relationship way

models/checks.go, models/components.go, models/config.go, query/components.go, query/config.go, query/resource_selector.go, tests/fixtures/dummy/config.go, tests/query_resource_selector_test.go, types/resource_selector.go, types/resource_selector_test.go
resolves: https://github.com/flanksource/duty/issues/585
=> feat: use field/label selector parser from apimachinery

query/resource_selector.go, tests/query_resource_selector_test.go
resolves: https://github.com/flanksource/duty/issues/643
resolves: https://github.com/flanksource/duty/issues/642
=> refactor: change the response of ResourceSelector search

query/config_traversal.go, tests/config_traversal_test.go, views/006_config_views.sql
Fixes: https://github.com/flanksource/duty/issues/640
=> feat: use directions in config traversal

query/config_traversal.go, tests/config_traversal_test.go
Fixes: https://github.com/flanksource/duty/issues/646
=> chore: add support for path in config traversal

query/config_changes.go, tests/config_changes_test.go, views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/652
=> support changes search without a catalog id

views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/654
=> feat: config detail changes

job/job.go
adding this to debug the sandbox env
=> feat: allow overwriting cleanup interval via property

job/job.go, job/job_test.go
* minor upgrade job logging
Noticed job histories weren't being cleared properly, so I've added a test.
=> test: status ring

go.mod, go.sum, hack/migrate/go.mod, hack/migrate/go.sum, query/config.go, tests/config_summary_test.go, tests/fixtures/dummy/config.go, tests/query_resource_selector_test.go
resolves: https://github.com/flanksource/duty/issues/672
=> feat: config summary new search query

job/job_test.go, models/canary.go, models/checks.go, models/components.go, models/config.go, models/connections.go, models/topology.go, schema/checks.hcl
don't allow gorm to update it as we have defaults in the db
resolves: https://github.com/flanksource/config-db/issues/487
=> fix: created at date

query/config.go
This was an edge case bug where the following query would generate an invalid sql query.
```sh
curl -s -X POST -u 'admin@local:admin' http://localhost:8080/catalog/summary \
--json '{
"groupBy": ["type", "namespace", "region"],
"deleted": false,
"changes": { "since": "" },
"analysis": { "since": "30d" },
"cost": "30d"
}'
```
What's weird is that it works fine if you group by `1` or `2` columns. As soon as you group by 3 columns (doesn't matter which), this bug happens. If you group by `4` columns then it works fine and then fails again if you group by `5` columns. _(probably fails if you have odd columns but I didn't test further)_
The bug particularly affects the `aggregated_health_count` `WITH` clause and in particular the select clause of that query. Here's the generated invalid query …
=> fix: config summary

job/check_status.go, views/013_check_summary.sql
resolves: https://github.com/flanksource/duty/issues/725
```
SELECT * FROM check_size_summary;
+--------------------------------------+--------------------------------------+------------------------+------------------------+-------+---------+----------+
| canary_id                            | id                                   | min_time               | max_time               | count | size    | avg_size |
|--------------------------------------+--------------------------------------+------------------------+------------------------+-------+---------+----------|
| b8fd8962-8f5b-40b5-b0ff-ab21430d3a2c | 018f32fe-c654-8941-a957-c16531bafb53 | 2024-05-01 07:11:48+00 | 2024-05-01 07:11:48+00 | 1     | 2548    | 2548     |
| 825b43dd-4cf2-4704-ac7a-6a48edbd7267 | …
```
=> feat: check_size_summary

models/components.go, schema/components.hcl, views/007_events.sql
resolves: https://github.com/flanksource/duty/issues/732
=> feat: config health trigger & add health to components

db.go
resolves: https://github.com/flanksource/duty/issues/742
=> feat: add HasMigrationsRun

views/015_job_history.sql
Using CTE to cache `notification_send_summary` significantly reduced **temp reads** & **writes**.
Brought down the execution time from `78s` to `<0.30ms`.
resolves: https://github.com/flanksource/duty/issues/738
=> fix: improve notifications_summary

query/commons.go, query/config.go
=> feat: add status filter in catalog api

connection/aws.go, connection/connection.go
=> chore: update connection ctx interface

models/components.go, models/config.go, schema/components.hcl, schema/config.hcl
related: https://github.com/flanksource/config-db/issues/534
=> fix: reconciliation of configs & components push the parents first

context/context.go, job/job.go, upstream/client.go, upstream/controllers.go
=> feat: add latency buckets in histogram

query/config_changes.go, tests/config_changes_test.go, views/006_config_views.sql
Fixes: https://github.com/flanksource/duty/issues/746
=> chore: add more filters in changes api

views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/735
=> feat: allow empty/none option on related_changes_recursive

models/config.go, views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/762
=> feat: add ready & health fields to related_configs_recursive

context/context.go
Fixes: https://github.com/flanksource/mission-control/issues/1009
=> chore: use sync map for context metrics

views/015_job_history.sql
resolves: https://github.com/flanksource/duty/issues/768
=> feat: job history view with resource name added

models/job_history.go, schema/system.hcl, tests/fixtures/dummy/all.go, tests/fixtures/dummy/job_history.go, tests/upstream_test.go, upstream/commands.go, upstream/jobs.go, upstream/upstream.go
Fixes: https://github.com/flanksource/mission-control/issues/701
=> feat: push job history to upstream

query/config_changes.go
Fixes: https://github.com/flanksource/duty/issues/784
@moshloop We already do MatchItem support for tag query: https://github.com/flanksource/duty/blob/62d48a2426a381864ffaf6ef477126adfcf6a360/query/config_changes.go#L231-L239
=> feat: add tags in config changes response

db.go, migrate/migrate.go, upstream/client.go
related: https://github.com/flanksource/mission-control/issues/1037
=> feat: support skipping migration on db init

tests/config_type_summary_test.go, tests/fixtures/dummy/config.go, tests/getters_test.go, tests/query_resource_selector_test.go
udpated dummy dataset as required by https://github.com/flanksource/canary-checker/pull/1881
=> chore: update dummy dataset

upstream/controllers.go
=> fix: missing label for counter

query/config_changes.go
resolves: https://github.com/flanksource/duty/issues/809
=> feat: agent_id filter to changes search

query/config_changes.go, tests/config_changes_test.go
resolves: https://github.com/flanksource/duty/issues/835
resolves: https://github.com/flanksource/duty/issues/836
=> feat: config changes filter by source

tests/upstream_test.go, upstream/jobs.go
resolves: https://github.com/flanksource/duty/issues/839
=> fix: error count on reconciliation

query/config_changes.go
resolves: https://github.com/flanksource/config-db/issues/650
=> fix: filtering by external created by

query/config_traversal.go, tests/config_traversal_test.go, views/006_config_views.sql
* order related_config_ids_recursive by increasing order of depth
* order related_configs_recursive by increasing order of depth
* exclude self when traversing
=> fix: config_traversal order

models/components.go, models/config.go, tests/upstream_test.go, upstream/commands.go
resolves: https://github.com/flanksource/mission-control/issues/1102
=> fix: fk error with config items & components

views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/859
=> feat: support include_deleted_configs opt on related_configs_recursive

models/source.go, schema/vars.hcl
=> chore: add new source push

query/resource_selector.go
=> refactor(resource selector): extract out the part where we set the where

db.go
Previous:
```
2024-06-25T18:59:57.372	ERROR	ERROR: update or delete on table "config_items" violates foreign key constraint 
"config_items_parent_id_fkey" on table "config_items" (SQLSTATE 23503)
```
New:
```
2024-06-25T18:59:57.372	ERROR	ERROR: update or delete on table "config_items" violates foreign key constraint 
"config_items_parent_id_fkey" on table "config_items" (SQLSTATE 23503): detail: Key (id)=(f5c71026-fcab-4709-
ae00-2edcc7e3086a) is still referenced from table "config_items".
```
Usage:
```go
if err := dutyCtx.DB().Exec(query).Error; err != nil {
err = duty.DBErrorDetails(err)
...
}
// or
if err := duty.DBErrorDetails(dutyCtx.DB().Exec(query).Error);  err != nil {
...
}
```
=> feat: add pg error details capture

tests/fixtures/dummy/config.go
=> chore: health of dummy config

query/config_changes.go, views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/891
=> fix: depth on config_relationships_recursive & validation in changes search

models/config.go, upstream/commands.go
resolves: https://github.com/flanksource/config-db/issues/710
=> fix(upstream): batch insertion of config items

connection/http.go
@moshloop Self merging this, let me know if any changes need to be made
=> chore: add http connection name handling

connection/http.go, connection/zz_generated.deepcopy.go, context/connection.go
@moshloop Self merging this FYI
=> chore: use envvar for http connection URL

tests/config_relationship_test.go, views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/920
=> fix: config relationship @depth=0

query/config_changes.go, views/006_config_views.sql
resolves: https://github.com/flanksource/mission-control/issues/1274
=> feat: return count & first observed in config changes

job/job.go
related: https://github.com/flanksource/config-db/issues/840
=> feat: job concurrency

api/config.go
@moshloop Self merging, this is breaking prod
=> fix: run migrations in mission control

connection/sftp.go, connection/smb.go
hydrate env vars even if the connection name isn't provided.
=> fix: improve hydration of SMB & SFTP connections

models/topology.go
Fixes: https://github.com/flanksource/canary-checker/issues/2013
=> chore: update topology on conflict clause

models/common.go, models/components.go, query/topology.go
=> chore: revamp component health logic

go.mod, job/cleanup.go
Fixes: https://github.com/flanksource/mission-control/issues/1317
=> fix: batchify agent job history cleanup

query/checks.go, query/components.go, query/config.go, query/resource_selector.go, relationship_selector.go, tests/getters_test.go, tests/query_resource_selector_test.go
resolves: https://github.com/flanksource/duty/issues/998
=> feat: limit on resource selector search

job/job.go
resolves: https://github.com/flanksource/duty/issues/1015
=> fix: exclude jitter duration

context/connection.go
related: https://github.com/flanksource/config-db/issues/887
fixes incomplete connection string validation
=> fix: return error on invalid connection string

job/cleanup.go
=> chore: speed up agent history cleanup job

tests/config_changes_test.go, views/030_config_changes.sql
related: https://github.com/flanksource/duty/pull/1021
=> feat: trigger on config_changes update

views/007_events.sql
resolves: https://github.com/flanksource/duty/issues/1050
=> feat: publish events on insertion of unhealthy & warning config items

models/notifications.go, schema/notifications.hcl, tests/notification_test.go, views/021_notification.sql
related: https://github.com/flanksource/mission-control/issues/1387
=> feat: dedup unsent notifications in history

connection/gcp.go
* return client from the connection
=> feat: support skipping TLS verification for GCS

schema/notifications.hcl, views/021_notification.sql
```
SELECT * FROM notification_silences_list\G
-[ RECORD 1 ]-------------------------
id              | 01920957-3de1-a4a8-a7ff-6120d4230365
namespace       | default
recursive       | <null>
description     | <null>
from            | 2024-09-19 13:57:45.409327+05:45
until           | 2024-09-19 15:57:45.409327+05:45
source          | UI
created_by      | <null>
created_at      | 2024-09-19 13:57:45.409327+05:45
updated_at      | 2024-09-19 13:57:45.409327+05:45
deleted_at      | <null>
resource_id     | 01919914-22e2-b38a-e66e-813a110aebd8
resource_icon   |
resource_type   | http
resource_health | unhealthy
resource_status | <null>
resource_name   | localhost check
resource_kind   | check
-[ RECORD 2 ]-------------------------
id              | 01920959-77b9-9b8d-fb4f-7e105bd0ee3c …
```
=> feat: notification silences list

models/playbooks.go, schema/playbooks.hcl
related: https://github.com/flanksource/mission-control/issues/1435
=> feat: spec on playbook runs

tests/config_type_summary_test.go
Fixes: https://github.com/flanksource/duty/issues/1049
=> chore: add test for n-day config summary

context/properties.go, echo/properties.go, tests/upstream_test.go
related: https://github.com/flanksource/mission-control/issues/1421
=> fix: properties endpoint

views/015_job_history.sql
related: https://github.com/flanksource/flanksource-ui/issues/2306
=> show errors on notifications_summary view

views/020_teams_triggers.sql, views/021_notification.sql, views/033_table_activity.sql
=> feat: table activity trigger for permissions

schema/agents.hcl, schema/config.hcl, schema/playbooks.hcl, schema/system.hcl
Fixes https://github.com/flanksource/mission-control/issues/1464
=> chore: add missing indexes

job/catalog.go, query/config.go, tests/config_relationship_test.go, tests/config_summary_test.go, tests/config_traversal_test.go, tests/config_type_summary_test.go, views/006_config_views.sql
Fixes: https://github.com/flanksource/mission-control/issues/1479
=> chore: remove analysis since from summary request and add 3d materialized view

models/canary.go
related: https://github.com/flanksource/canary-checker/issues/2199
=> fix: canary on conflict clause

schema/notifications.hcl
resolves: https://github.com/flanksource/mission-control/issues/1501
=> fix: delete_old_config_items

models/playbooks.go, schema/playbooks.hcl
related: https://github.com/flanksource/mission-control/issues/1506
=> fix: change pending -> pending_approval

upstream/commands.go, upstream/jobs.go
resolves: https://github.com/flanksource/duty/issues/1126
=> feat: remove fk errors from reconcile summary

schema/openapi/canary.schema.json, schema/openapi/canary.spec.schema.json, schema/openapi/component.schema.json, schema/openapi/component.spec.schema.json, schema/openapi/health_catalog.schema.json, schema/openapi/health_databasebackupcheck.schema.json, schema/openapi/health_exec.schema.json, schema/openapi/health_folder.schema.json, schema/openapi/incident-rules.schema.json, schema/openapi/notification.schema.json, schema/openapi/playbook-spec.schema.json, schema/openapi/playbook.schema.json, schema/openapi/scrape_config.schema.json, schema/openapi/scrape_config.spec.schema.json, schema/openapi/topology.schema.json, schema/openapi/topology.spec.schema.json
run make update-openapi-schemas
=> chore: update OPENAPI schemas

views/006_config_views.sql
Fixes: https://github.com/flanksource/duty/issues/1166
=> fix: return single row for config detail

upstream/jobs.go
to 
```
config_changes:
success: 9
foreign_error: null
```
=> chore: cleaner summary

connection/environment.go, tests/fixtures/dummy/all.go, tests/fixtures/dummy/config.go, tests/upstream_test.go
=> fix: kubernetes connection setup from scraper

schema/openapi/playbook-spec.schema.json, schema/openapi/playbook.schema.json
need to update the openapi schema for playbooks so the test https://github.com/flanksource/mission-control/pull/1589 passes
=> chore: unmerged playbook spec

query/config.go
Fixes: https://github.com/flanksource/duty/issues/1170
=> fix: group by for catalog summary

types/resource_selector.go
related: https://github.com/flanksource/duty/issues/1202
=> fix: resource selector docs for CRD

views/006_config_views.sql
resolves: https://github.com/flanksource/duty/issues/1213
=> fix: configs view should return new config items.

models/notifications.go, models/playbooks.go, schema/notifications.hcl
related: https://github.com/flanksource/mission-control/issues/1420
=> feat: playbook as notification recipient

models/canary.go, models/checks.go, models/components.go, models/config.go, query/resource_selector.go, query/topology.go, tests/fixtures/dummy/components.go, tests/query_resource_selector_test.go, types/envvar.go, types/resource_selector.go, types/resource_selector_test.go, types/zz_generated.deepcopy.go
resolves: https://github.com/flanksource/duty/issues/1231
=> feat(resource selector): support health filter

query/grammar/grammar_test.go
Fixes: https://github.com/flanksource/duty/issues/1241
=> chore: improve grammar test

models/permission.go, models/playbooks.go, schema/permissions.hcl, types/resource_selector.go, views/033_table_activity.sql, views/036_permission.sql
related: https://github.com/flanksource/mission-control/issues/1700
=> feat: table schemas for permission & permission group

query/resource_selector.go
it's being used in canary checker
=> fix: make SetResourceSelectorClause public

models/playbooks.go, schema/playbooks.hcl
related: https://github.com/flanksource/mission-control/issues/1719
=> feat: playbook run parent

query/grammar/grammar_parser.go, query/grammar/grammar_test.go, query/grammar/grammer.go, query/grammar/grammer.peg, tests/query_resource_selector_test.go
Fixes: https://github.com/flanksource/duty/issues/1246
=> fix: grammar should parse * and no field words

query/models.go, tests/fixtures/dummy/config.go, tests/query_resource_selector_test.go
=> feat: resource selector search in config and labels

context/properties.go, schema/openapi/canary.schema.json, schema/openapi/canary.spec.schema.json, schema/openapi/component.schema.json, schema/openapi/component.spec.schema.json, schema/openapi/connection.schema.json, schema/openapi/health_catalog.schema.json, schema/openapi/health_exec.schema.json, schema/openapi/incident-rules.schema.json, schema/openapi/notificationsilence.schema.json, schema/openapi/permission.schema.json, schema/openapi/permissiongroup.schema.json, schema/openapi/playbook-spec.schema.json, schema/openapi/playbook.schema.json, schema/openapi/scrape_config.schema.json, schema/openapi/scrape_config.spec.schema.json, schema/openapi/topology.schema.json, schema/openapi/topology.spec.schema.json
`This is just to trigger a new release`
=> update schema and fix formatting in properties

connection/environment.go
resolves: https://github.com/flanksource/mission-control/issues/1779
=> fix: allow access to cluster when scrapers don't have custom kubeconfig

models/checks.go, models/common.go, models/components.go, models/config.go
related: https://github.com/flanksource/duty/issues/1286
=> add new interfaces for models that have tags and labels

query/grammar/grammar.go, query/grammar/grammar.peg, query/grammar/grammar_parser.go, query/grammar/grammar_test.go, query/resource_selector.go
resolves: https://github.com/flanksource/duty/issues/1298
=> feat: make resource selector search prefix search by default

connection/gcp.go
It returns gcs client.
We now have a GCSConnection
=> fix: remove gcp client

connection/environment.go
resolves: https://github.com/flanksource/mission-control/issues/1848
=> fix: kubeconfig template

models/playbooks.go, schema/playbooks.hcl
related: https://github.com/flanksource/mission-control/issues/1846
=> feat: retry playbook actions

connection/connection.go, models/common.go, models/connections.go, models/permission.go, rbac/custom_functions.go
related: https://github.com/flanksource/mission-control/issues/638
=> feat: permission for connections

query/models.go, tests/query_resource_selector_test.go
=> fix: check supported columns for resource selector search

job/job.go, query/config_cache.go, query/jobs.go, query/models.go
resolves: https://github.com/flanksource/duty/issues/1238
=> feat: support case insensitive suffix type matching

.gitignore, connection/environment.go, go.mod, kubernetes/k8s.go, kubernetes/testdata/kubeconfig.yaml, kubernetes/utils.go, kubernetes/utils_test.go, shell/shell.go, tests/connection_test.go, tests/fixtures/dummy/config.go, tests/testdata/my-kube-config.yaml
resolves: https://github.com/flanksource/mission-control/issues/1929
=> feat: add connection context to shell errors

views/015_job_history.sql
* Added a new field `last_failed_at`
* Fixed sent count (don't count pending or skipped ones)
related: https://github.com/flanksource/is-healthy/issues/165
=> feat: add last failed notification time to notifications_summary view

.gitignore, models/playbooks.go, rbac/policy/policy.go
related: https://github.com/flanksource/mission-control/issues/1911
=> feat: Playbook cancellation

views/021_notification.sql
related: https://github.com/flanksource/flanksource-ui/issues/2492
=> feat: add playbook run and playbook details to notification send history summary

rbac/objects.go, views/018_playbooks.sql
A new function to get actions from child playbook runs as well
=> feat: get_playbook_run_actions function

models/playbooks.go
related: https://github.com/flanksource/mission-control/issues/1881
=> feat: Playbook child runs

query/config_changes.go, views/006_config_views.sql
related: https://github.com/flanksource/flanksource-ui/issues/2496
=> feat: support filtering changes from deleted configs

views/006_config_views.sql
related: https://github.com/flanksource/flanksource-ui/pull/2509
=> feat: agent name in config details

views/018_playbooks.sql
agents were not being fetched properly
=> fix: get_playbook_run_actions

models/playbooks.go, schema/playbooks.hcl
related: https://github.com/flanksource/mission-control/issues/1956
=> feat: Playbook run timeout

rbac/custom_functions.go, rbac/custom_functions_test.go, shutdown/shutdown.go
resolves: https://github.com/flanksource/duty/issues/1379
=> fix: ABAC check

views/021_notification.sql
related: https://github.com/flanksource/flanksource-ui/issues/2522
=> feat: resource health & status in notification send history

.github/workflows/release.yml, postq/event.go
resolves: https://github.com/flanksource/duty/issues/1362
=> fix: dummy commit to create a new release

models/notifications.go, tests/notification_test.go
resolves: https://github.com/flanksource/duty/issues/1407
We were not properly forming the condition for Unique Constraint.
=> fix: on conflict clause in notification_group_resources in postgres v14

views/018_playbooks.sql
we need it to calculate the cost incurred by all the actions.
related: https://github.com/flanksource/mission-control/issues/1829
=> feat: return playbook action result

views/018_playbooks.sql
related: https://github.com/flanksource/mission-control/issues/2043
=> feat: return artifacts on rpc/get_playbook_run_actions

kubernetes/dynamic.go, tests/kubernetes_test.go
resolves: https://github.com/flanksource/duty/issues/1415
=> fix: kubenetes QueryResource support for non-namespaced resources

kubernetes/dynamic.go
```
{"time":"2025-04-24T05:00:17.594728011Z","level":"ERROR","msg":"[Canary] failed to schedule [Canary/default/exchange-rates] failed to schedule job: expected exactly 5 fields, found 3: [every 30 @minutes]"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x4a38526]
goroutine 840 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.35.0/trace/span.go:467 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc017406d20, {0x0, 0x0, 0xc0175c1f58?}) …
```
=> fix: panic due to nil rest mapper when fetched from cache

models/playbooks.go
related: https://github.com/flanksource/mission-control/issues/2064
=> fix(playbook actions): result layout on error

go.mod, pubsub/subscribe.go, pubsub/types.go
=> chore: add gcp connection handling in pubsub

models/config_access.go, schema/config_access.hcl
config access must be deleted with the scraper
=> feat: config scraper on access models

.editorconfig, context/connection_suite_test.go, logs/cloudwatch/search.go, logs/gcpcloudlogging/cloud_logging.go, logs/k8s/logs.go, logs/loki/loki.go, logs/loki/types.go, logs/opensearch/search.go, logs/opensearch/types.go
=> fix: cloud logging panic

views/022_agents.sql
@moshloop @adityathebe 
The 61 second was taken from frontend, let me know if that needs to be changed
=> chore: add status and health in agent_summary

go.mod, go.sum, query/commons.go, query/grammar/filters.go, query/template_test.go, tests/query_resource_selector_test.go
Depends on https://github.com/flanksource/commons/pull/267
=> feat(search): add glob support and fix match query tests

tests/triggers_test.go, views/007_events.sql
resolves: https://github.com/flanksource/duty/issues/1481
=> feat: config.degraded event

query/notification_types.go
related: https://github.com/flanksource/flanksource-ui/issues/2582
=> fix: notification summary search by prefix

context/context.go, db.go, go.mod, tests/view_migration_test.go, view/db.go
resolves: https://github.com/flanksource/mission-control/issues/2186
=> feat: view table migration with atlas

view/view.go
```yaml
apiVersion: mission-control.flanksource.com/v1
kind: View
metadata:
name: pods
namespace: mc
spec:
columns:
- name: name
type: string
primaryKey: true
- name: namespace
type: string
primaryKey: true
- name: url
for: name
type: url
queries:
pod:
configs:
types:
- Kubernetes::Pod
mapping:
name: row.name
namespace: row.namespace
url: >
"https://example.com/" + .name
```
=> feat: helper columns

tests/testdata/views/deployments.yaml, tests/testdata/views/pipelines.json, tests/testdata/views/pipelines.yaml, tests/view_test.go, view/columns.go, view/db.go
resolves: https://github.com/flanksource/duty/issues/1503
=> fix: always read the view table in view.spec.columns order

dataquery/sqlite_functions.go, tests/testdata/views/pipelines.yaml, view/columns.go
* fix SQLITE function for `Mi`
=> feat: Gauge updates

dataquery/sqlite_functions.go, dataquery/sqlite_test.go
* use kubernetes parser
* rename sqlite functions
=> fix: sqlite functions

view/columns.go, view/zz_generated.deepcopy.go
https://github.com/flanksource/mission-control/issues/2272
=> feat: view column icon

models/config.go
=> chore: get config item struct from config summary

views/036_permission.sql
=> feat: permissions summary source
