views/001_roles.sql
views/002_seed.sql
views/011_users.sql

This fixes a race condition where kratos migration failed since identities table was already created by us

fix: do not create identities table, create trigger if it already exists

---

types/types.go

With this we can avoid a lot of boilerplate code when working with json based structs with gorm. We wouldn't have to write Scan/Value() funcs everytime.
```go
type Person struct {
ID         uuid.UUID        `json:"id" gorm:"default:generate_ulid()"`
Name       string           `json:"name,omitempty"`
Properties PersonProperties `json:"properties,omitempty"`
}
type PersonProperties struct {
Car   string `json:"car,omitempty"`
Wheel string `json:"wheel,omitempty"`
}
func (p PersonProperties) Value() (driver.Value, error) {
return types.GenericStructValue(p, true)
}
func (p *PersonProperties) Scan(val any) error {
return types.GenericStructScan(&p, val)
}
```

feat: add generic gorm scan/value funcs

---

views/013_updated_at_column_trigger.sql

On row updates, the `updated_at` column value is set to `Now()`.
Closes https://github.com/flanksource/duty/issues/48

Added a trigger to all tables that have "updated_at" column.

---

models/config.go

This will help in removing the incomplete config scraper model in config-db. It also adds a before create hook so we don' store empty UUIDs

feat: added config scraper model

---

fixtures/dummy/config_analysis.go
models/config.go
schema/config.hcl
views/006_config_views.sql

* The default queries using config analysis filters only open analyses

feat: add scraper id to config analysis

---

topology.go
topology_test.go

Fixes: https://github.com/flanksource/canary-checker/issues/997

fix: return only one component when id is provided in topology

---

fixtures/dummy/config_analysis.go
models/config.go

Resolves: https://github.com/flanksource/duty/issues/83
Need to trigger release

feat: add config analysis types

---

schema/system.hcl

Since default priority was 0, all the responder/notification and team events were getting starved
We not set lower priority explicitly for upstream push and by default events will have a higher priority than those

fix: set default event priority to high to prevent starvation

---

models/checks.go
upstream/reconcile.go
upstream/upstream.go

Migrated upstream logic from incident commander.
Also, added support for reconciling check statuses.
It'll be used by both canary check and by incident commander.

feat: add upstream and reconcile logic from incident commander

---

schema/config.hcl

Fixes: https://github.com/flanksource/incident-commander/issues/488
Regarding upstream push,
So we had a bad spec for config scraper which caused all config_scrapers to fail which caused all config_items to fail. Since we don't use pointers for `source` and `spec` fields, these should be not null in the database as well

chore: change config_scrapers.{spec,source} to not null

---

models/playbooks.go
schema/playbooks.hcl
views/007_events.sql
views/018_playbooks.sql

- Support playbook runs for checks
- put approval spec changes and new approvals to event queue instead of just publishing a notification.

feat: playbook runs for checks

---

db.go

I'm now fairly certain the incident-commander new deployment is failing due to issues with connection pooling. We have about 12 event consumers now.
When some of those event consumers are not running, the health check runs fine.

chore: increase pool max conn size

---

models/agents.go
models/canary.go
schema/notifications.hcl

- canary.AsMap had fields in Caps.
- make notification template column nullable because we have default values.

chore: add JSON tags to canary struct

---

views/007_events.sql
views/012_changelog.sql

Async events, like `notification.send`, are created from the application; unlike sync events which are created with DB triggers. Due to this reason, we do not have PG notify triggers when async events are inserted. As a result, async event consumers never run in real-time and rely on the 1 minute timeout. (This was fine so far, because no matter which event was inserted, the pgnotify was picked up by all consumers. But now we have specific pg notify channels)
Instead of publishing pgnotify during insertion from multiple trigger functions, this PR adds a trigger on the event_queue table itself.
---
Also 
* added ON CONFLICT clauses on insertion to event queue
* Ignore adding to event queue if component.status = unknown
---
Resolves: https://github.com/flanksource/canary-checker/issues/1259

fix: event_queue fixes

---

models/notifications.go
schema/notifications.hcl
views/007_events.sql
views/020_teams_triggers.sql
views/021_notification.sql

* setup new pg notifications when tables are updated

feat: add error column to notifications table

---

db.go
go.mod
go.sum

We use `NewPgxPool` for multiple databases now (in mission control tests)

fix: pgx pool init

---

envvar.go
fixtures/dummy/components.go
fixtures/expectations/topology_child_tree.json
fixtures/expectations/topology_cluster_component_tree.json
fixtures/expectations/topology_depth_1_root_tree.json
fixtures/expectations/topology_depth_2_root_tree.json
fixtures/expectations/topology_root_tree.json
fixtures/expectations/topology_tree_with_agent_id.json
fixtures/expectations/topology_tree_with_label_filter.json
fixtures/expectations/topology_tree_with_owner_filter.json
fixtures/expectations/topology_tree_with_status_filter.json
suite_test.go
topology.go
topology_test.go

Resolves:  https://github.com/flanksource/duty/issues/285

feat: minimal topology details for rest of the children

---

views/010_topology.sql

Parents were being duplicated in the result which led to duplication in the card view

fix: use distinct for children and parents in topology query

---

migrate/migrate.go

This was the reason for permission errors on newly created envs

chore: grant privileges to postgrest_api

---

types/types.go

@moshloop Self-merging this
Fix for double-quotes in status reason:

fix: double quote in null string type

---

go.mod
go.sum
hack/migrate/go.sum
views/012_changelog_trigger_func.sql
views/012_changelog_triggers_checks.sql
views/012_changelog_triggers_others.sql
views/012_changelog_triggers_scrapers.sql

This way config-db, canary-checker can only apply changelog triggers that they need.

feat: divide changelog migration script

---

types/latency.go

it was removed because it was never populated but canary-checker uses it

chore: add Rolling1H to latency

---

views/015_job_history.sql

resolves: https://github.com/flanksource/duty/issues/413

feat: modify notifications_summary

---

query/topology.go
tests/fixtures/dummy/components.go
tests/fixtures/expectations/topology_tree_with_desc_sort.json
tests/fixtures/expectations/topology_tree_with_sort.json
tests/topology_test.go

Closes: https://github.com/flanksource/duty/issues/442

feat: add sorting support for topology query

---

context/context.go
job/job.go

Incorrect namespace (due to overriding of object meta) was being used in topologies, causing connections to break (they depend on ctx.GetNamespace())

fix: only set job meta if unset

---

upstream/upstream.go

Fixes: https://github.com/flanksource/duty/issues/404

chore: order components and config_items by path length to handle parent fkey

---

upstream/commands.go

Root tables (topologies, canaries & config_scrapers) can be saved individually instead of batches because there aren't that many of them and they don't need to be synced frequently.
The benefit is that on failure we can identify which item caused the error.

fix: save root tables one by one instead of in batches

---

tests/upstream_test.go
upstream/client.go
upstream/controllers.go
upstream/event_consumer.go
upstream/jobs.go
upstream/reconcile.go
upstream/upstream.go

This PR 
- creates a middleware for all agent authentication. (works for both access token based & query param based authentication)
- supplying the agent name via query param is more streamlined and doesn't need to be set manually in all places.

feat: agent auth middleware

---

Makefile
schema/openapi/canary.spec.schema.json
schema/openapi/component.spec.schema.json
schema/openapi/topology.spec.schema.json

This fixes a few issues that are due to inconsistencies, some schema definitions are under definitions properties and others are under $def property and this breaking the canary, topology and component schemas, but not config specs

fix: fix broken schemas reference to definitions

---

models/playbooks.go
schema/playbooks.hcl

This is for errors that are not related to actions. Example:
- db errors when fetching the playbook
- when a non existent playbook id is supplied
- when a playbook delay expression is invalid (the delay is in action but its parsed by the run consumer.)

feat: add error column to playbooks

---

.gitignore
models/config.go
tests/config_relationship_test.go
views/006_config_views.sql

resolves: https://github.com/flanksource/duty/issues/558

modify related configs views to return configs as columns instead of json

---

query/commons.go
query/config_changes.go
tests/config_changes_test.go

- add pagination (sortby, pagesize, page)
- return the catalog name as well
- filter by
- severity
- `to` date
- inclusion of deleted configs

feat: add pagination and more filtering in catalog changes

---

context/connection.go
context/connection_test.go

pass in the connection's properties during hydration. It also supports env var strings.
---
it was need because right now we only have three fields that can store env vars (username, password & certificate). If I needed to save a postgres connection host and database, for example, it wasn't possible.
Now it's possible to store the connection as `postgres://$(username):$(password)@$(properties.host):$(properties.port)/$(properties.database)` and the connection properties can be
```json
{
"properties": {
"database": "secret://postgres/database",
"host": "secret://postgres/host"
}
}
```

feat: pass in the properties while templating connection

---

schema/config.hcl

`idx_config_items_agent` is covered by `idx_config_items_name`

fix: remove duplicate index

---

api/errors.go
api/http.go
db.go
hack/migrate/go.mod
hack/migrate/go.sum
job/check_status.go
models/checks.go
models/common.go
models/components.go
models/config.go
tests/upstream_test.go
upstream/client.go
upstream/commands.go
upstream/controllers.go
upstream/jobs.go
views/016_check_status.sql

The plan is that if the upstream gets any fk constraint error
- it does the insert/update one by one and keeps a list of all the items that failed due to fk constraint error
- the agent then marks the parent(s) of those failed items as `is_pushed=false`
- In the next round of reconciliation, the conflict will get resolved (or we could restart the round immediately after this round ends)
resolves: https://github.com/flanksource/duty/issues/689

feat: handle foreign key error during reconciliation

---

query/config_changes.go
views/006_config_views.sql

Fixes https://github.com/flanksource/duty/issues/708

chore: include created by details in catalog change api

---

job/cleanup.go
job/job.go
job/job_test.go

resolves: https://github.com/flanksource/duty/issues/727
1. The stale running job histories of singleton jobs will now be cleared by the status ring itself.
2. For stale running job histories of deleted resources _(i.e. the job doesn't run anymore)_, the cleanup job in mission control will call `CleanupStaleHistoryJob` with a smaller stale age _(probably 4 hours)_ just for running statuses.

feat: clear out stale running job histories for singleton jobs

---

views/006_config_views.sql

These triggers were cleared up in the AWS cluster, but for some reason it remained on the Demo cluster but only for two tables: config_changes, config_analysis.
```
SELECT  properties->>'table', COUNT(*) FROM event_queue WHERE name = 'push_queue.create' GROUP BY properties->>'table'
+-----------------+-------+
| ?column?        | count |
|-----------------+-------|
| config_analysis | 1333  |
| config_changes  | 57254 |
+-----------------+-------+
```

fix: cleanup trigger that adds push_queue.create events

---

models/config.go
tests/config_relationship_test.go
views/006_config_views.sql

* the number of columns returned by the view & the number of columns used in the recursive CTE didn't match
* in outgoing relationship flip the parent & child
resolves: https://github.com/flanksource/duty/issues/812

fix: related_configs_recursive

---

api/http.go
upstream/client.go
upstream/commands.go
upstream/controllers.go
upstream/jobs.go

resolves: https://github.com/flanksource/duty/issues/828
Upstream was sending `api.HttpError` but we were unmarshalling to `api.Error`

fix: upstream error propagation

---

models/components.go
models/config.go
tests/config_relationship_test.go
upstream/controllers.go

resolves: https://github.com/flanksource/duty/issues/807
resolves: https://github.com/flanksource/duty/issues/834
By setting the gorm struct tags, gorm handles the `WHERE` clause.

fix: handle composite primary key when deleting relationships

---

db.go
go.mod
go.sum
upstream/jobs.go

resolves: https://github.com/flanksource/config-db/issues/637

fix: retry on deadlock

---

job/job_test.go
models/job_history.go
tests/job_test.go
tests/setup/common.go

@moshloop @adityathebe 
I think we can remove the status: "FINISHED"
We almost always treat success and finished the same way, and in all the queries we have to handle for both of these. In our usecase, a job without errors should be considered SUCCESS
What do you think ?

chore: remove job status: finished

---

job/controllers.go

```json
[
{
"id": "default/localhost",
"name": "Canary",
"schedule": "@every 30s",
"resource_id": "08cc3286-c0fb-479c-a0ca-8c4c6ae3181f",
"resource_type": "canary",
"last_ran": "0001-01-01T00:00:00Z",
"next_run": "2024-06-18T18:41:05+05:45",
"next_run_in": "21.701406407s"
},
{
"id": "default/adityathebe.com",
"name": "Canary",
"schedule": "@every 30s",
"resource_id": "21720f2f-3e85-4480-a81a-f8240bdce8f7",
"resource_type": "canary",
"last_ran": "0001-01-01T00:00:00Z",
"next_run": "2024-06-18T18:41:05+05:45",
"next_run_in": "21.701401688s"
},
{
"id": "default/pod-exit-code-check",
"name": "Canary",
"schedule": "@every 1m",
"resource_id": "a28245c8-b53c-4ecf-98da-47c2c6b80dec",
"resource_type": "canary",
"last_ran": "0001-01-01T00:00:00Z",
"next_run": "2024-06-18T18:41:35+05:45", …
```

feat: add a new handler to expose cron entries

---

models/checks.go
models/config.go
types/resource_selector.go

changed the func signature for `GetStatus()` as component status can now return err

fix: resource selectable

---

pkg/kube/labels/selector.go
pkg/kube/labels/selector_test.go

This is required to support looking up labels with key like `aws:cloudformation:stack-id`

feat: remove label key validation

---

tests/upstream_test.go
upstream/jobs.go

resolves: https://github.com/flanksource/duty/issues/804
- added reconcile summary
- when a table fails to reconcile, only skip those tables that depend on it

feat(upstream): add reconcile summary and reconcile table groups and dependencies

---

types/resource_selector.go

```
/home/yash/Work/duty/types/resource_selector.go:29:2: encountered struct field "Scope" without JSON tag in type "ResourceSelector"
```

fix: add json tags for scope

---

job/job.go
models/job_history.go

We have 8-12 rows of success history created in a 1 minute

chore: push success history

---

job/job.go
tests/job_test.go

canary-checker needs the cron entries to be `cron.Job` instead of `cron.FuncJob` so it can extract the resource ID.

fix: use job struct instead of cron.FuncJob

---

hack/migrate/main.go
views/010_topology.sql

resolves: failed to query rest of the children: ERROR: column "health_expr" does not exist (SQLSTATE 42703)
`health_expr` exists however the topology view needs to be recreated.
A small diff on the migration file should trigger the run.

fix: topology view

---

models/config.go

root config_items have `NULL` path. When ordering by `LENGTH(path) ASC` they appear at the end.
so we try to reconcile the children first and always hit foreign key error.

fix: handle `NULL` paths when reconciling `config_items`

---

views/006_config_views.sql

notifications on `config.updated` is literally a spam without this. This event is triggered on every scrape due to changes to `last_scraped_time`.
On health updates as well, we are basically triggering `config.updated` & `config.<health>` events.

fix: config.updated events

---

.github/workflows/release.yml

@moshloop Do we need caching in this step ? we anyways have to download a new duty package anyway

chore: remove cache from release

---

views/030_config_changes.sql

we were reseting the created_at time of config changes everytime
@moshloop This seems to be the reason why we had sporadically failing tests.
resolves: https://github.com/flanksource/duty/issues/1034

fix: config change update trigger

---

models/components.go

We are getting this error while pushing topologies
```
error pushing topology: error pushing topology[Tenant/org-86mkxfst1do7/t-test1] to https://telemetry.app.flanksource.com/push/topology, non 2xx response received: 500 Internal Server Error
{"error":"error saving components: ERROR: duplicate key value violates unique constraint 
\"components_topology_id_type_name_parent_id_key\" (SQLSTATE 23505): detail: Key (topology_id, type, name, 
parent_id)=(0be593be-3d79-406b-8168-224b20efb83b, JobHistory, AggregateCheckStatuses1d, 018fe70b-3927-e69e-
f8ab-328d78f75547) already exists."} 
```
Although the unique clause exists, the order is different
I tried locally and order should not matter but still doing this anyway

fix: change on conflict clause order

---

query/config.go
tests/config_summary_test.go
tests/fixtures/dummy/config.go
tests/suite_test.go
upstream/commands.go

resolves: https://github.com/flanksource/duty/issues/1006

feat: support include/exclude for labels filter in config summary

---

models/components.go
models/topology.go

PostgreSQL does not support multiple on conflict
The OnConflict was added on ID to handle pushed topology saves but we don't really need it

fix: use single on conflict clause

---

postq/pg/router.go
postq/pg/router_test.go

The notify router expected the pg notify payload to be in <route> <actual payload> format.
We allow consumers to provide custom extractor & let them decided how to extract the route & the actual payload from the original notify payload.
This is required for `playbook_action_updates` PG notify where we extract the route & payload from a JSON payload.

feat: allow custom route extractor on pg notify router

---

models/notifications.go
schema/notifications.hcl
views/015_job_history.sql

related: https://github.com/flanksource/mission-control/issues/1394

feat: notification name & namespace

---

shell/shell.go
shell/shell_test.go

resolves: https://github.com/flanksource/duty/issues/1016

feat: hide os shell envs

---

views/015_job_history.sql

don't count failed notifications that have reached max attempts as Pending

fix: notification summary

---

query/topology.go

Fixes: https://github.com/flanksource/canary-checker/issues/2143

fix: add health to component topology select clause

---

job/job.go
upstream/controllers.go

It wasn't working correctly since we were passing an uninitialized channel which is nil and does not get passed by reference.
The main issue was that we were adding items to an always uninitialized channel and that was blocking the whole operation

fix: start job history channel fetch before adding items

---

types/common.go
upstream/jobs.go

We were getting empty errors as `json.Marshal` always marshals `error` type as `{}` due to it being an interface
To do: Also if summary.Error is non nil, job history returns success since we do not update error count, this needs to be fixed in mission-control
Have fixed this, but UI is now having an issue rendering it
Error details:
```json
{
"errors": "job_history: failed to push job_history to upstream: upstream server returned error status[500]: Internal Server Error; ",
"summary": {
"checks": {
"success": 25
},
"components": {
"success": 103
},
"job_history": {
"error": "failed to push job_history to upstream: upstream server returned error status[500]: Internal Server Error"
},
"config_items": {
"success": 28
},
"check_statuses": {
"success": 81
},
"config_changes": {
"success": 35 …
```

fix: reconcile error handling

---

tests/config_gitops_test.go

This was the reason for the flakiness

fix: call summary refresh job in gitops source test

---

schema/playbooks.hcl

Error on aws
```json
{"time":"2024-10-16T04:15:52.308735642Z","level":"ERROR+1","msg":"failed to apply schema migrations: applied 6 changes and then failed: drop enum type \"playbook_run_status\": pq: cannot drop type playbook_run_status because other objects depend on it"}
```
Seems like migration does not update column types ? we dont use that type anywhere but getting this from db
```sql
mission_control=# SELECT                                                                                     
table_schema,
table_name,
column_name
FROM
information_schema.columns
WHERE
column_default LIKE '%playbook_run_status%';
-[ RECORD 1 ]+---------------------
table_schema | public
table_name   | playbook_run_actions
column_name  | status
```
Also, we should update the tool's version ? we are on …

fix: undo drop of playbook_run_status

---

views/005_component_views.sql

Fixes: https://github.com/flanksource/mission-control-registry/issues/321

fix: concat config_id and path for lookup_component_config_query

---

query/getters.go
query/resource_selector.go
types/resource_selector.go

For using catalog lookup in k8s topology chart, we need to be able to distinguish b/w clusters, currently we do that via kubeconfig using kubernetes lookup.
We need to allow scope to be selectable by namespace/name to have the same functionality

feat: allow namespace/name for scope in resource selector

---

context/connection.go
context/connection_test.go

Fixes: https://github.com/flanksource/duty/issues/941

chore: trim space/newline around connection username,password and url

---

views/006_config_views.sql

Previously:
```
Planning Time: 2.682 ms
Execution Time: 173.179 ms
```
After change:
```
Planning Time: 2.133 ms
Execution Time: 4.294 ms
```
Verified with multiple config items
Also, this query takes 2nd highest IO time in AWS cluster
Fixes: https://github.com/flanksource/duty/issues/1141

chore: optimize config_detail view using materialized views

---

views/021_notification.sql

a superfluous change in the file to run it during migration.
```
{
"code": "42P01",
"details": null,
"hint": null,
"message": "relation \"public.notification_send_history_summary\" does not exist"
}
```
resolves: https://github.com/flanksource/mission-control/issues/1548

fix: bring back notification_send_history_summary

---

postq/pg/router.go
postq/pg_consumer.go

discard unnecessary pgnotify notifications.
For every event we're currently calling `ConsumeUntilEmpty`. 
If 10 events are published in burst, we call `ConsumeUntilEmpty` for each of those 10 notifications.
This PR fixes that behavior by simply discarding additional signals.

feat: improve event consumers

---

shutdown/shutdown.go
shutdown/shutdown_test.go

related: https://github.com/flanksource/canary-checker/issues/2221

feat: shutdown priority levels

---

query/getters.go
views/033_table_activity.sql

publish pg notify on playbook table updates to keep the getter cache in sync
related: https://github.com/flanksource/mission-control/issues/1563

feat: table playbook activity pg notify

---

views/006_config_views.sql

Fixes: https://github.com/flanksource/duty/issues/1185

chore: remove duplicates in related_changes_recursive

---

migrate/dependency.go
migrate/dependency_test.go
migrate/migrate.go
migrate/migrate_test.go
tests/migration_dependency_test.go
views/006_config_views.sql
views/021_notification.sql

resolves: https://github.com/flanksource/duty/issues/1193

feat: migration dependencies

---

views/029_config_triggers.sql

Causing a few config-db test cases to break, and I don't think we need to create a change event for newly created items

fix: do not create change for new items with unknown health

---

context/context.go
kubernetes/k8s.go

adds `NewClientFromPathOrConfig` so the caller doesn't have to check if the config is kubeconfig path or the actual kubeconfig.

chore: refactor kubernetes client constructor

---

views/021_notification.sql

we need to recreate the view `notification_send_history_summary` so it returns `playbook_run_id` column

dummy change in script to trigger migration

---

models/notifications.go
schema/notifications.hcl

related: https://github.com/flanksource/mission-control/issues/1684

feat: store recipient details in notification send history

---

tests/migration_dependency_test.go
tests/setup/common.go

* test fails anyway even with exit code 0
* fix migration dependency test which was sporadically failing

fix: don't call os.Exit() on tests

---

views/031_casbin_effect.sql

```
failed to initialize rbac: 
error creating rbac enforcer: invalid policy rule size: expected 6, got 5, 
rule: [everyone database.kratos * deny true]
setting v5 as empty string didn't fix this. 
Casbin probably still sees the row as 5 columns, so setting it as "na".
Policies formed from permissions table have a valid UUID for v5 and mission-control uses uuid.Validate() to filter them out.
```

fix: casbin migration

---

tests/migration_dependency_test.go

```
The entire test suite is ran with RLS enabled.
One of the tests (migration dependency test) ran the migration that disabled RLS.
```

fix: sporadically failing RLS test

---

schema/playbooks.hcl

Both `playbook_run_id` and `agent_id` are NULL on agents.

fix: remove check on playbook run actions

---

context/context.go
query/resource_selector.go
rls/payload.go
rls/payload_test.go

related: https://github.com/flanksource/mission-control/issues/1750

fix: resource selector cache scoped per user when RLS is enabled

---

models/permission.go
models/permission_test.go
models/playbooks.go

The condition on the policy shouldn't be using double quotes.
Add `.AsMap()` to `RBACAttribute`.
When `RBACAttribute` object was directly passed to casbin, it returned the following error
```
Unable to access unexported field 'playbook' in 'r_obj'
```
This happend despite the fact that the struct and the fields were exported and also the fields had json tags.

fix: permission to casbin policy mapping

---

models/common.go
models/permission.go
models/permission_test.go
models/playbooks.go

We reference the fields directly (i.e. Go field names) - not the json field names.
This avoids all `.AsMap()` and `.ToMap()` serializations.
Also, explains the `Unable to access unexported field 'playbook'` error in https://github.com/flanksource/duty/pull/1275.

fix: Don't serialize ABAC attributes. Use the object directly inside casbin

---

connection/environment.go
connection/git.go
shell/shell.go

fix: Support kubeconfig path
related: https://github.com/flanksource/mission-control-registry/issues/372

fix: allow setting up env from multiple connections at once. Example: needing to setup EKS kubeconfig & the aws connection.

---

query/checks.go
query/components.go
query/config.go
query/models.go
query/playbooks.go
query/resource_selector.go
tests/config_changes_test.go
tests/fixtures/dummy/config.go
tests/getters_test.go
tests/query_resource_selector_test.go

resolves: https://github.com/flanksource/duty/issues/1285

MatchItem supports on all resource selector fields

---

models/checks.go
models/common.go
models/components.go
models/config.go
query/resource_selector.go
tests/query_resource_selector_test.go
types/resource_selector.go
types/resource_selector_test.go

resolves: https://github.com/flanksource/duty/issues/1310

feat: support grammar in resource selector .Matches

---

models/checks.go
models/common.go
models/components.go
models/config.go
query/commons.go
query/config.go
query/grammar/filters.go
query/grammar/grammar.go
query/grammar/grammar.peg
query/grammar/grammar_parser.go
query/grammar/query.go
query/models.go
query/resource_selector.go
tests/query_resource_selector_test.go
types/resource_selector.go
types/resource_selector_test.go

`resourceSelector.Matches()` needs to use `grammar.Parse` but that creates an import cycle between `types` and `grammar` packages.

make `pkg/grammar` free from any mission-control dependencies

---

go.mod
go.sum
query/check_details.go
tests/query_check_details_test.go

Fixes: https://github.com/flanksource/canary-checker/issues/1986

fix: latency calculation in check

---

query/grammar/filters.go
query/grammar/query.go
query/models.go
schema/apply.go
schema/components.hcl
schema/config.hcl
tests/fixtures/dummy/config.go
tests/query_resource_selector_test.go
views/002_seed.sql

resolves: https://github.com/flanksource/duty/issues/1305
```sql
incident_commander> EXPLAIN (ANALYZE, BUFFERS) SELECT name, type, tags
FROM config_items
WHERE  tags_values ?| ARRAY['immich']
+----------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                             |
|----------------------------------------------------------------------------------------------------------------------------------------|
| Bitmap Heap Scan on config_items  (cost=12.95..122.39 rows=31 width=101) (actual time=0.014..0.041 rows=31 loops=1)                    |
|   Recheck Cond: (tags_values ?| …
```

feat: unkeyed search on tags & properties

---

views/021_notification.sql

related: https://github.com/flanksource/mission-control/issues/1838
got a lot of `config_changes_config_id_external_change_id_key` violation errors.
I assume it's due to multiple changes being inserted in a single transaction.
```
12:27:08.21 DBG (job. process pending notifications) [notification.send] config.unhealthy
12:27:08.216 ERR (db) ERROR >=[1ms] [rows:0] ERROR: duplicate key value violates unique constraint "config_changes_config_id_external_change_id_key" (SQLSTATE 23505) UPDATE "notification_send_history" SET "status"=$1$ WHERE id IN ($2$)
12:27:08.217 ERR (db) ERROR >=[1ms] [rows:0] ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02) UPDATE "notification_send_history" SET "error"='failed to save notification status as sent: …
```

fix: config changes for notification

---

query/config_changes.go
query/resource_selector.go
tests/getters_test.go
tests/query_resource_selector_test.go

Fixes: https://github.com/flanksource/canary-checker/issues/2452

chore: use common function for field, label and tag selectors

---

connection/environment.go

related: https://github.com/flanksource/mission-control/issues/1929
The kubernetes connection needs to be hydrated when setting up the connection.
Else, `.valueStatic` is always empty and we were creating an empty `kubeconfig` file.

fix: kubernetes connection setup

---

query/check_details.go

Fixes https://github.com/flanksource/canary-checker/issues/2510

fix: avoid passing empty slices to stat.Quantile

---

postq/event.go
tests/event_queue_test.go

Sometimes the planner would use `Nested Loop Semi Join` which would cause all the events to be deleted even with a LIMIT of 1. The sync consumer is expecting just one event so it uses the first from the list. All the other events get deleted but only one gets processed.
This isn't reproducible consistently.
```
EXPLAIN (ANALYZE, BUFFERS) DELETE FROM event_queue
WHERE id IN (
SELECT id FROM event_queue
ORDER BY priority DESC, created_at ASC
FOR UPDATE SKIP LOCKED
LIMIT 1
)
RETURNING *
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN …
```

fix: dropping events

---

go.mod
postq/event.go

related: https://github.com/flanksource/mission-control/issues/1987
Maybe, events are being dropped. This should never happen.

panic when more events, than the requested amount, is fetched

---

models/notifications.go
views/021_notification.sql

Unlike other deduplication like with status = repeated, silenced, deduplication of skipped notifications are different.
For repeated/silenced/inhibited notifications:
- We either create a new record, or
- Update the count of an existing record with the same status
For skipped notifications:
- A notification record already exists with status "pending" or "evaluating-waitfor"
- When deduplicating, we need to:
1. Increment the count of the existing skipped record, AND
2. Delete the corresponding "pending" or "evaluating-waitfor" send history

feat: dedup skipped notifications

---

views/021_notification.sql

With two inhibition rules like this, a pod could be inhibited by different resources
```
PVC 
-> Pod
Node
-> Pod
```
When pod gets inhibited by PVC, we want to dedup to the send history that was inhibited by the PVC.

fix: dedup inhibited

---

connection/environment.go

Fixes: https://github.com/flanksource/mission-control/issues/2061

fix: inject kube env vars for exec action with config item

---

tests/config_changes_test.go

Another notification test would sometimes run before this test and create new `config_changes`.

fix: failing test "FindCatalogChanges"

---

views/006_config_views.sql

* frontend uses it. the postgREST query cannot join with config_scrapers table due to new changes involving config_access `(Could not embed because more than one relationship was found for 'config_detail' and 'config_scrapers')`

feat: add scraper detail to config_detail view

---

.github/workflows/test.yaml
tests/incident_summary_test.go
tests/setup/common.go

This pull request adds a test matrix for PostgreSQL versions 14, 15, and 16 in the GitHub Actions workflow. The changes are made in the `.github/workflows/test.yaml` file, where a matrix strategy is defined for the `migrate` job. This allows the tests to run against multiple PostgreSQL versions, ensuring compatibility and stability across these versions. The specific tags and SHA values for each PostgreSQL version are included to ensure the correct images are used during the tests.
---
> This pull request was co-created with Cosine Genie
Original Task: [duty/fq4655uoayk6](https://cosine.sh/flanksource/duty/task/fq4655uoayk6)
Author: Moshe Immerman

Add Test Matrix for PostgreSQL 14, 15, and 16

---

Makefile
go.mod
models/config.go
query/template.go
query/template_test.go
types/resource_selector.go

resolves: https://github.com/flanksource/mission-control/issues/2144
**Bug Summary:**
The issue was in query/template.go where the code needed to convert a map back to a ConfigItem struct. The problem occurred because the `Config` field in ConfigItem is stored as a JSON string (or pointer to string), but when represented in a map, the config data is actually a nested map object.
The original code used manual JSON marshaling/unmarshaling to convert the map to ConfigItem, but this failed because it couldn't properly handle the type mismatch between the map's config field (map[string]any) and the struct's Config field (*string).
**Solution:**
~~Added a new `FromMap` method on ConfigItem that specially handles the config field by detecting if it's a map and converting it to a JSON string~~ …

fix: json marshalling/unmarshalling of config items in matchQuery

---

models/canary_test.go
models/config_test.go
models/connections_test.go
models/suite_test.go

`ginkgo` imports `Label` so we couldn't define our own Label type in `models` package.

chore: remove dot imports from gomega

---

context/context.go
dataquery/merge.go
dataquery/merge_test.go
dataquery/sqlite.go
dataquery/sqlite_test.go

gorm's `.Create(map[string]any)` would panic if the value was not a primitive type.

fix: dataquery

---

view/columns.go
view/db.go

when reading from postgres table, we must convert the values into a type defined by the column.
Example: 
* type `gauge` is saved to db as JSONB. When the data is read, the postgres driver reads it into []uint8. We need to convert that to json.RawMessage or types.JSON() for proper serialization to the web client.
* type `duration` is saved as bigint. When the data is read, it must be casted to time.Duration()

fix: reading view table into go types

---

upstream/jobs.go

```
{"time":"2025-09-05T03:16:25.819249545Z","level":"ERROR","msg":"ERROR >=\u001b[33m[3ms] \u001b[34;1m[rows:0]\u001b[0m ERROR: column \"created_at\" does not exist (SQLSTATE 42703) UPDATE \"view_panels\" SET \"is_pushed\"=$1$ WHERE created_at >= NOW() - INTERVAL '7 days' OR updated_at >= NOW() - INTERVAL '7 days' AND deleted_at IS NULL","logger":"db"}
{"time":"2025-09-05T03:16:25.819487873Z","level":"ERROR","msg":"ResetIsPushed{https://mc.org-t7jalrtfpbbl.workload-prod-eu-01.flanksource.com} error updating is_pushed for table[{00000000-0000-0000-0000-000000000000  00000000-0000-0000-0000-000000000000 %!s(bool=false) <nil> }]: ERROR: column \"created_at\" does not exist (SQLSTATE 42703)","logger":"job. reset is pushed"}
```

fix: handle ResetIsPushed for view_panels

---

query/connections.go
query/models.go
query/resource_selector.go
tests/fixtures/dummy/all.go
tests/fixtures/dummy/connections.go
tests/query_resource_selector_test.go

related: https://github.com/flanksource/flanksource-ui/pull/2635
we need this to support the search queries in resources field in the permission table.
Example: Search connections by type=aws

feat(resource selector): Support for playbooks and connections

---

canary/controller.go
query/check_summary.go
views/034_rls_enable.sql

For now: setup RLS on canaries on labels because we don't have `tags` and `agent_id` on canaries.
This effectively hides all canaries for the guest user (for now)

feat: RLS canaries
